apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: yc-mk8s-node-configuration
  labels:
    app.kubernetes.io/name: yc-mk8s-node-configuration
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: yc-mk8s-node-configuration
  template:
    metadata:
      labels:
        app.kubernetes.io/name: yc-mk8s-node-configuration
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
      initContainers:
      - name: iptables-rules-updater
        image: &image cr.yandex/crphethshoa49p577uqh/yc-mk8s-node-configuration:1718198847
        command:
          - /usr/local/bin/iptables-rules-updater
        args:
          - --log-level=debug
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "NET_RAW"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: host
          mountPath: /host
      containers:
      - name: containerd-registry-mirrors-updater
        image: *image
        command:
          - /usr/local/bin/containerd-registry-mirrors-updater
        args:
          - --log-level=debug
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: host
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
